version: 2
updates:
- package-ecosystem: gradle
  directory: "/core"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  reviewers:
  - pinussilvestrus
  assignees:
  - pinussilvestrus
- package-ecosystem: gradle
  directory: "/web"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  reviewers:
  - pinussilvestrus
  assignees:
  - pinussilvestrus
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.3
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.3
- package-ecosystem: npm
  directory: "/web/src/main/resources/public/bpmnjs"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - ">= 4.a, < 5"
